import { NullEngine } from "@babylonjs/core/Engines/nullEngine";
import { FreeCamera } from "@babylonjs/core/Cameras/freeCamera";
import { StandardMaterial } from "@babylonjs/core/Materials/standardMaterial";
import { PBRMaterial } from "@babylonjs/core/Materials/PBR/pbrMaterial";
import { Vector3 } from "@babylonjs/core/Maths/math.vector";
import { CreateBox } from "@babylonjs/core/Meshes/Builders/boxBuilder";
import { Scene } from "@babylonjs/core/scene";
import { describe, expect, it, vi } from "vitest";
import { createUltraMaterialAdapter } from "../../src/client/render/UltraLightingPresentation";
import { registerStaticUniformVertexColors, usesUniformVertexColors } from "../../src/client/render/UltraVertexColorOptimization";

describe("ultra static vertex color work", () => {
  it("revokes color work for GPU-only index updates, shared frozen materials and throwing mutations", async () => {
    const engine = new NullEngine();
    const scene = new Scene(engine);
    const camera = new FreeCamera("camera", new Vector3(0, 0, -5), scene);
    camera.setTarget(Vector3.Zero());
    const mesh = CreateBox("building-walls-dynamic-indices", {}, scene);
    const colors = new Float32Array(mesh.getTotalVertices() * 4).fill(0.5);
    for (let vertex = 0; vertex < 4; vertex += 1) colors[vertex * 4] = 0.3;
    mesh.setVerticesData("color", colors);
    const indices = [...mesh.getIndices()!];
    mesh.setIndices(indices, null, true);
    const geometry = mesh.geometry!;
    const update = vi.fn(geometry.updateIndices.bind(geometry));
    geometry.updateIndices = update;
    mesh.material = new StandardMaterial("surface", scene);
    const shared = mesh.clone("building-walls-shared")!;
    const throwing = CreateBox("building-walls-throw", {}, scene);
    throwing.setVerticesData("color", new Float32Array(throwing.getTotalVertices() * 4).fill(0.5));
    throwing.material = new StandardMaterial("throw-surface", scene);
    throwing.geometry!.updateIndices = () => { throw new Error("index upload failed"); };
    try {
      createUltraMaterialAdapter(scene).convertScene();
      const material = mesh.material as PBRMaterial;
      await material.forceCompilationAsync(mesh);
      await (throwing.material as PBRMaterial).forceCompilationAsync(throwing);
      scene.render(); material.freeze();
      expect(usesUniformVertexColors(mesh)).toBe(true);
      const changed = indices.slice(); changed[1] = 4;
      geometry.updateIndices(changed, 0, true);
      expect(update).toHaveBeenCalledWith(changed, 0, true);
      expect([...mesh.getIndices()!]).toEqual(indices);
      expect(usesUniformVertexColors(mesh)).toBe(false);
      expect(usesUniformVertexColors(shared)).toBe(false);
      scene.render();
      for (const owner of [mesh, shared]) expect(owner.subMeshes![0]!.effect!.defines).not.toContain("#define ULTRA_VERTEX_GAMMA");
      registerStaticUniformVertexColors(mesh);
      expect(usesUniformVertexColors(mesh)).toBe(false);
      geometry.updateIndices(indices);
      expect(update).toHaveBeenLastCalledWith(indices);
      expect(() => throwing.geometry!.updateIndices(throwing.getIndices()!, 2, true)).toThrow("index upload failed");
      expect(usesUniformVertexColors(throwing)).toBe(false);
      scene.render();
      expect(throwing.subMeshes![0]!.effect!.defines).not.toContain("#define ULTRA_VERTEX_GAMMA");
    } finally { scene.dispose(); engine.dispose(); }
  });

  it("isolates constant triangle colors from gradients, mutable surfaces, decals and loot without changing shared geometry", async () => {
    const engine = new NullEngine();
    const scene = new Scene(engine);
    const camera = new FreeCamera("camera", new Vector3(0, 0, -5), scene);
    camera.setTarget(Vector3.Zero());
    const make = (name: string, gradient = false, updatable = false) => {
      const mesh = CreateBox(name, {}, scene);
      const colors = new Float32Array(mesh.getTotalVertices() * 4).fill(0.5);
      if (gradient) colors[0] = 0.2;
      mesh.setVerticesData("color", colors, updatable);
      mesh.material = new StandardMaterial("surface", scene);
      return mesh;
    };
    const uniform = make("building-walls-uniform"), gradient = make("building-walls-gradient", true);
    const mutable = make("building-walls-mutable", false, true), unknown = make("unknown");
    const plant = make("tree-foliage-template"), lod = make("ultra-tree-foliage-lod");
    plant.addLODLevel(80, lod);
    const instance = plant.createInstance("tree-instance");
    const loot = make("loot");
    loot.material!.name = "loot-model-material-armor-1";
    const originalColors = [...plant.getVerticesData("color")!];
    const originalIndices = [...plant.getIndices()!];
    let forwarded = 0;
    uniform.geometry!.onGeometryUpdated = () => { forwarded += 1; };
    try {
      createUltraMaterialAdapter(scene).convertScene();
      expect([uniform, plant, lod, instance].every(usesUniformVertexColors)).toBe(true);
      expect([gradient, mutable, unknown, loot].some(usesUniformVertexColors)).toBe(false);
      expect([...plant.getVerticesData("color")!]).toEqual(originalColors);
      expect([...plant.getIndices()!]).toEqual(originalIndices);
      const material = uniform.material as PBRMaterial;
      gradient.material = material;
      await material.forceCompilationAsync(uniform);
      await material.forceCompilationAsync(gradient);
      scene.render();
      const first = uniform.subMeshes![0]!.effect!;
      const second = gradient.subMeshes![0]!.effect!;
      expect(first).not.toBe(second);
      expect(first.defines).toContain("#define ULTRA_VERTEX_GAMMA");
      expect(second.defines).not.toContain("#define ULTRA_VERTEX_GAMMA");
      const plugin = material.pluginManager!.getPlugin("UltraGammaVertexColor")!;
      const defines = uniform.subMeshes![0]!.materialDefines!;
      defines.DECAL = true;
      plugin.prepareDefines(defines, scene, uniform);
      expect(defines.ULTRA_VERTEX_GAMMA).toBe(false);
      defines.DECAL = false; defines.DETAIL = true;
      plugin.prepareDefines(defines, scene, uniform);
      expect(defines.ULTRA_VERTEX_GAMMA).toBe(false);
      defines.DETAIL = false;
      plugin.prepareDefines(defines, scene, uniform);
      expect(defines.ULTRA_VERTEX_GAMMA).toBe(true);
      await (loot.material as PBRMaterial).forceCompilationAsync(loot);
      expect(loot.subMeshes![0]!.effect!.defines).toContain("#define ULTRA_LOOT_FILL");
      expect(loot.subMeshes![0]!.effect!.defines).not.toContain("#define ULTRA_VERTEX_GAMMA");
      uniform.setVerticesData("color", new Float32Array(uniform.getTotalVertices() * 4).fill(0.6));
      expect(forwarded).toBe(1);
      expect(usesUniformVertexColors(uniform)).toBe(false);
      scene.render();
      expect(uniform.subMeshes![0]!.effect!.defines).not.toContain("#define ULTRA_VERTEX_GAMMA");
      registerStaticUniformVertexColors(uniform);
      expect(usesUniformVertexColors(uniform)).toBe(false);
      uniform.setIndices([0, 1, uniform.getTotalVertices()]);
      expect(usesUniformVertexColors(uniform)).toBe(false);
      registerStaticUniformVertexColors(uniform);
      expect(usesUniformVertexColors(uniform)).toBe(false);
    } finally { scene.dispose(); engine.dispose(); }
  });
});
